# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - bluerov2/imu_joint
    - bluerov2/pose_sensor_default_joint
    - bluerov2/pressure_joint
    - bluerov2/thruster_0_joint
    - bluerov2/thruster_1_joint
    - bluerov2/thruster_2_joint
    - bluerov2/thruster_3_joint
    - bluerov2/thruster_4_joint
    - bluerov2/thruster_5_joint
    - hdt/drive1_joint
    - hdt/drive2_joint
    - hdt/drive3_joint
    - hdt/drive4_joint
    - hdt/drive5_joint
    - hdt/drive6_joint
    - hdt/pincer_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: bluerov2/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hdt/drive1_joint
      - hdt/drive2_joint
      - hdt/drive3_joint
      - hdt/drive4_joint
      - hdt/drive5_joint
      - hdt/drive6_joint
  - name: bluerov2/hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hdt/pincer_joint

bluerov2:      
  arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - hdt/drive1_joint
      - hdt/drive2_joint
      - hdt/drive3_joint
      - hdt/drive4_joint
      - hdt/drive5_joint
      - hdt/drive6_joint
    gains:
      hdt/drive1_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      hdt/drive2_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      hdt/drive3_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      hdt/drive4_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      hdt/drive5_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      hdt/drive6_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - hdt/pincer_joint
    gains:
      hdt/pincer_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1